language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - ./vendor/phpunit/phpunit/phpunit -c ./tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls